# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import linuxcnc_fleet.fleet_pb2 as fleet__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetServiceStub(object):
    """Services

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/GetStatus',
                request_serializer=fleet__pb2.MachineId.SerializeToString,
                response_deserializer=fleet__pb2.MachineStatus.FromString,
                _registered_method=True)
        self.SubscribeStatus = channel.unary_stream(
                '/linuxcnc_fleet.FleetService/SubscribeStatus',
                request_serializer=fleet__pb2.MachineId.SerializeToString,
                response_deserializer=fleet__pb2.MachineStatus.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/SetMode',
                request_serializer=fleet__pb2.SetModeRequest.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.SetExecution = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/SetExecution',
                request_serializer=fleet__pb2.ExecutionCommand.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.SetMachineState = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/SetMachineState',
                request_serializer=fleet__pb2.MachineStateCommand.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/Start',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/Stop',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.FeedHold = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/FeedHold',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.Continue = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/Continue',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.HomeAll = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/HomeAll',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.HomeAxis = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/HomeAxis',
                request_serializer=fleet__pb2.HomeAxisRequest.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.SendMdiCommand = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/SendMdiCommand',
                request_serializer=fleet__pb2.MdiCommand.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.LoadProgram = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/LoadProgram',
                request_serializer=fleet__pb2.ProgramPath.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.StepForward = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/StepForward',
                request_serializer=fleet__pb2.Empty.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/GetPosition',
                request_serializer=fleet__pb2.PositionRequest.SerializeToString,
                response_deserializer=fleet__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.ListHalComponents = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/ListHalComponents',
                request_serializer=fleet__pb2.ListHalRequest.SerializeToString,
                response_deserializer=fleet__pb2.HalComponentList.FromString,
                _registered_method=True)
        self.ReadHalPin = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/ReadHalPin',
                request_serializer=fleet__pb2.HalPinRead.SerializeToString,
                response_deserializer=fleet__pb2.HalPinValue.FromString,
                _registered_method=True)
        self.WriteHalPin = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/WriteHalPin',
                request_serializer=fleet__pb2.HalPinWrite.SerializeToString,
                response_deserializer=fleet__pb2.Result.FromString,
                _registered_method=True)
        self.SubscribeHalPins = channel.unary_stream(
                '/linuxcnc_fleet.FleetService/SubscribeHalPins',
                request_serializer=fleet__pb2.HalPinSubscribe.SerializeToString,
                response_deserializer=fleet__pb2.HalPinUpdate.FromString,
                _registered_method=True)
        self.GetErrors = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/GetErrors',
                request_serializer=fleet__pb2.GetErrorsRequest.SerializeToString,
                response_deserializer=fleet__pb2.ErrorList.FromString,
                _registered_method=True)
        self.SubscribeErrors = channel.unary_stream(
                '/linuxcnc_fleet.FleetService/SubscribeErrors',
                request_serializer=fleet__pb2.MachineId.SerializeToString,
                response_deserializer=fleet__pb2.ErrorEvent.FromString,
                _registered_method=True)
        self.GetMachineInfo = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/GetMachineInfo',
                request_serializer=fleet__pb2.MachineId.SerializeToString,
                response_deserializer=fleet__pb2.MachineInfo.FromString,
                _registered_method=True)
        self.GetIniParam = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/GetIniParam',
                request_serializer=fleet__pb2.IniParamRequest.SerializeToString,
                response_deserializer=fleet__pb2.IniParamValue.FromString,
                _registered_method=True)
        self.ListPrograms = channel.unary_unary(
                '/linuxcnc_fleet.FleetService/ListPrograms',
                request_serializer=fleet__pb2.ListProgramsRequest.SerializeToString,
                response_deserializer=fleet__pb2.ProgramList.FromString,
                _registered_method=True)


class FleetServiceServicer(object):
    """Services

    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMachineState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FeedHold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Continue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HomeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HomeAxis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMdiCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadProgram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHalComponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadHalPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteHalPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeHalPins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIniParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrograms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=fleet__pb2.MachineId.FromString,
                    response_serializer=fleet__pb2.MachineStatus.SerializeToString,
            ),
            'SubscribeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeStatus,
                    request_deserializer=fleet__pb2.MachineId.FromString,
                    response_serializer=fleet__pb2.MachineStatus.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=fleet__pb2.SetModeRequest.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'SetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExecution,
                    request_deserializer=fleet__pb2.ExecutionCommand.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'SetMachineState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMachineState,
                    request_deserializer=fleet__pb2.MachineStateCommand.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'FeedHold': grpc.unary_unary_rpc_method_handler(
                    servicer.FeedHold,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'Continue': grpc.unary_unary_rpc_method_handler(
                    servicer.Continue,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'HomeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.HomeAll,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'HomeAxis': grpc.unary_unary_rpc_method_handler(
                    servicer.HomeAxis,
                    request_deserializer=fleet__pb2.HomeAxisRequest.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'SendMdiCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMdiCommand,
                    request_deserializer=fleet__pb2.MdiCommand.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'LoadProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadProgram,
                    request_deserializer=fleet__pb2.ProgramPath.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'StepForward': grpc.unary_unary_rpc_method_handler(
                    servicer.StepForward,
                    request_deserializer=fleet__pb2.Empty.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=fleet__pb2.PositionRequest.FromString,
                    response_serializer=fleet__pb2.PositionResponse.SerializeToString,
            ),
            'ListHalComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHalComponents,
                    request_deserializer=fleet__pb2.ListHalRequest.FromString,
                    response_serializer=fleet__pb2.HalComponentList.SerializeToString,
            ),
            'ReadHalPin': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadHalPin,
                    request_deserializer=fleet__pb2.HalPinRead.FromString,
                    response_serializer=fleet__pb2.HalPinValue.SerializeToString,
            ),
            'WriteHalPin': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteHalPin,
                    request_deserializer=fleet__pb2.HalPinWrite.FromString,
                    response_serializer=fleet__pb2.Result.SerializeToString,
            ),
            'SubscribeHalPins': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeHalPins,
                    request_deserializer=fleet__pb2.HalPinSubscribe.FromString,
                    response_serializer=fleet__pb2.HalPinUpdate.SerializeToString,
            ),
            'GetErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrors,
                    request_deserializer=fleet__pb2.GetErrorsRequest.FromString,
                    response_serializer=fleet__pb2.ErrorList.SerializeToString,
            ),
            'SubscribeErrors': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeErrors,
                    request_deserializer=fleet__pb2.MachineId.FromString,
                    response_serializer=fleet__pb2.ErrorEvent.SerializeToString,
            ),
            'GetMachineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineInfo,
                    request_deserializer=fleet__pb2.MachineId.FromString,
                    response_serializer=fleet__pb2.MachineInfo.SerializeToString,
            ),
            'GetIniParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIniParam,
                    request_deserializer=fleet__pb2.IniParamRequest.FromString,
                    response_serializer=fleet__pb2.IniParamValue.SerializeToString,
            ),
            'ListPrograms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrograms,
                    request_deserializer=fleet__pb2.ListProgramsRequest.FromString,
                    response_serializer=fleet__pb2.ProgramList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linuxcnc_fleet.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linuxcnc_fleet.FleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetService(object):
    """Services

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/GetStatus',
            fleet__pb2.MachineId.SerializeToString,
            fleet__pb2.MachineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SubscribeStatus',
            fleet__pb2.MachineId.SerializeToString,
            fleet__pb2.MachineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SetMode',
            fleet__pb2.SetModeRequest.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SetExecution',
            fleet__pb2.ExecutionCommand.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMachineState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SetMachineState',
            fleet__pb2.MachineStateCommand.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/Start',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/Stop',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FeedHold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/FeedHold',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Continue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/Continue',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HomeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/HomeAll',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HomeAxis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/HomeAxis',
            fleet__pb2.HomeAxisRequest.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMdiCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SendMdiCommand',
            fleet__pb2.MdiCommand.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/LoadProgram',
            fleet__pb2.ProgramPath.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/StepForward',
            fleet__pb2.Empty.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/GetPosition',
            fleet__pb2.PositionRequest.SerializeToString,
            fleet__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHalComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/ListHalComponents',
            fleet__pb2.ListHalRequest.SerializeToString,
            fleet__pb2.HalComponentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadHalPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/ReadHalPin',
            fleet__pb2.HalPinRead.SerializeToString,
            fleet__pb2.HalPinValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteHalPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/WriteHalPin',
            fleet__pb2.HalPinWrite.SerializeToString,
            fleet__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeHalPins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SubscribeHalPins',
            fleet__pb2.HalPinSubscribe.SerializeToString,
            fleet__pb2.HalPinUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/GetErrors',
            fleet__pb2.GetErrorsRequest.SerializeToString,
            fleet__pb2.ErrorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc_fleet.FleetService/SubscribeErrors',
            fleet__pb2.MachineId.SerializeToString,
            fleet__pb2.ErrorEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/GetMachineInfo',
            fleet__pb2.MachineId.SerializeToString,
            fleet__pb2.MachineInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIniParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/GetIniParam',
            fleet__pb2.IniParamRequest.SerializeToString,
            fleet__pb2.IniParamValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrograms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetService/ListPrograms',
            fleet__pb2.ListProgramsRequest.SerializeToString,
            fleet__pb2.ProgramList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FleetGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiscoverMachines = channel.unary_unary(
                '/linuxcnc_fleet.FleetGatewayService/DiscoverMachines',
                request_serializer=fleet__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=fleet__pb2.MachineList.FromString,
                _registered_method=True)
        self.RouteMachine = channel.unary_unary(
                '/linuxcnc_fleet.FleetGatewayService/RouteMachine',
                request_serializer=fleet__pb2.MachineId.SerializeToString,
                response_deserializer=fleet__pb2.GatewayRoute.FromString,
                _registered_method=True)
        self.BroadcastCommand = channel.unary_unary(
                '/linuxcnc_fleet.FleetGatewayService/BroadcastCommand',
                request_serializer=fleet__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=fleet__pb2.BroadcastResult.FromString,
                _registered_method=True)
        self.SubscribeAllStatus = channel.unary_stream(
                '/linuxcnc_fleet.FleetGatewayService/SubscribeAllStatus',
                request_serializer=fleet__pb2.SubscribeAllRequest.SerializeToString,
                response_deserializer=fleet__pb2.MachineStatus.FromString,
                _registered_method=True)
        self.RegisterMachine = channel.unary_unary(
                '/linuxcnc_fleet.FleetGatewayService/RegisterMachine',
                request_serializer=fleet__pb2.RegisterRequest.SerializeToString,
                response_deserializer=fleet__pb2.RegisterResponse.FromString,
                _registered_method=True)


class FleetGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DiscoverMachines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeAllStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterMachine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiscoverMachines': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverMachines,
                    request_deserializer=fleet__pb2.DiscoverRequest.FromString,
                    response_serializer=fleet__pb2.MachineList.SerializeToString,
            ),
            'RouteMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteMachine,
                    request_deserializer=fleet__pb2.MachineId.FromString,
                    response_serializer=fleet__pb2.GatewayRoute.SerializeToString,
            ),
            'BroadcastCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastCommand,
                    request_deserializer=fleet__pb2.BroadcastRequest.FromString,
                    response_serializer=fleet__pb2.BroadcastResult.SerializeToString,
            ),
            'SubscribeAllStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAllStatus,
                    request_deserializer=fleet__pb2.SubscribeAllRequest.FromString,
                    response_serializer=fleet__pb2.MachineStatus.SerializeToString,
            ),
            'RegisterMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMachine,
                    request_deserializer=fleet__pb2.RegisterRequest.FromString,
                    response_serializer=fleet__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linuxcnc_fleet.FleetGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linuxcnc_fleet.FleetGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DiscoverMachines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetGatewayService/DiscoverMachines',
            fleet__pb2.DiscoverRequest.SerializeToString,
            fleet__pb2.MachineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetGatewayService/RouteMachine',
            fleet__pb2.MachineId.SerializeToString,
            fleet__pb2.GatewayRoute.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetGatewayService/BroadcastCommand',
            fleet__pb2.BroadcastRequest.SerializeToString,
            fleet__pb2.BroadcastResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeAllStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc_fleet.FleetGatewayService/SubscribeAllStatus',
            fleet__pb2.SubscribeAllRequest.SerializeToString,
            fleet__pb2.MachineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc_fleet.FleetGatewayService/RegisterMachine',
            fleet__pb2.RegisterRequest.SerializeToString,
            fleet__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
